config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # namespace :api do
  #   post 'users/sign_in' => 'users#login'
  #   get 'user/:id/posts' => 'posts#index'
  #   get 'comments' => 'comments#index'
  #   post 'comments/create' => 'comments#create'
  # end

  namespace :api, defaults: { format: :json } do
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index show] do
        resources :comments, only: %i[index show create]
      end
    end
  
end

  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  get 'posts/new', to: 'posts#new'
  post 'posts', to: 'posts#create'
  post 'likes/:post_id', to: 'likes#create'
  post 'comments/:post_id', to: 'comments#create'
  resources :users, only: [:index, :show] do
  resources :posts, :show, only: [:index, :show, :new, :create, :destroy] do
    resources :likes, only: [:create]
    resources :comments, only: [:index, :create, :new , :destroy]
  end
  end

  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  belongs_to :user

  after_save :update_post_user_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_post_user_counter
    user.increment!(:posts_counter)
  end

  def five_most_recent_comments
    comments.includes(:user).order(created_at: :desc).first(5)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @posts = Post.where(user_id: @user.id)
      respond_to do |format|
        format.json { render json: @posts, status: :ok }
      end
    else
      respond_to do |format|
        format.json { render json: 'Please sign in or add the token', status: :ok }
      end
    end
  end

  def show
    if params[:post_id]
      @post = Post.find(params[:post_id])
      respond_to do |format|
        format.json { render json: @post, status: :ok }
      end
    else
      respond_to do |format|
        format.json { render json: 'Please sign in or add the token', status: :ok }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(:posts).find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
    @user = current_user
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    post = current_user.posts.new(params.require(:post).permit(:title, :text))
    respond_to do |format|
      format.html do
        if post.save
          flash[:success] = 'Post saved successfully'
          redirect_to "/users/#{current_user.id}/posts"
        else
          flash.now[:error] = 'Error: Post could not be saved'
          render :new, locals: { post: }
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end
end

app/views/posts/index.html.erb
<h1 class="users_show_header">User Posts Details</h1>
<div class="users_wrapper">
  <div class="users_show_main_container">
    <%= image_tag(@user.photo || "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=455&q=80", class: "user_image_card") %>
    <div class="user_info_container">
      <h2> <%= @user.name %> </h2>
      <div class="user_info_posts_counter">
        Number of posts:
        <%= @user.posts_counter || 0 %>
      </div>
    </div>
    <div class="create_post_wrapper">
    <a href="/posts/new" class="create_new_post_link">
      Create New Post
    </a>
  </div>
  </div>
</div>

<div class="users_wrapper">
  <% @user.three_most_recent_posts.each do |post| %>
    <a href="/users/<%= @user.id %>/posts/<%= post.id %>" class="user_index_container">
      <div class="user_info">
        <h2><%= post.title %></h2>
        <p class="post_text"><%= post.text %></p>
        <div class="user_info__posts_counter">
          Comments:
          <%= post.comments_counter || 0 %>
          , Likes:
          <%= post.likes_counter || 0 %>
        </div>
      </div>
    </a>

    <%= form_with url: "/likes/#{post.id}", html: {class: "new_like"} do |form| %>
      <%= form.submit "Like", class: "new_like_btn" %>
    <% end %>

    <%= form_with url: "/comments/#{post.id}", scope: :comment, html: {class: "new_comment"} do |form| %>
      <%= form.text_area :text, placeholder: "Enter comment text", class: "form_comment" %>
      <%= form.submit "Add Comment", class: "new_comment_btn" %>
    <% end %>
    <div class="comments_info"> 
      <% if post.five_most_recent_comments.length > 0 %>
        <% post.five_most_recent_comments.each do |comment| %>
          <div class="comment_info">
            <h4> <%= comment.user.name %>'s comment: </h4> 
            &nbsp;&nbsp;
            <p class ="comment_text"> <%= comment.text %> </p>
          </div>
        <% end %>
      <% else %>
        <p> No comments exist yet </p>
      <% end %>
    </div>
    <br>
    <hr />
    <br>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="form_container">
  <%= form_with model: @post, url: '/posts', html: {class: "new_post"} do |form| %>
    <div class="control_container">
      <%= form.label :title %><br>
      <%= form.text_field :title, class: "form_control", placeholder: "Enter post title" %>
    </div>
    <div class="control_container">
      <%= form.label :text %><br>
      <%= form.text_area :text, class: "form_control", placeholder: "Enter post text" %>
    </div>
    <div class="control_container button_container">
      <%= form.submit "Post", class: "submit_btn" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="users_wrapper">
    <div class="users_index_main_container">
      <div class="user_info">
        <h1><%= @post.title %> by <%= @post.user.name %></h1>
        <div class="user_info_posts_counter">
          Comments:
          <%= @post.comments_counter || 0 %>
          , Likes:
          <%= @post.likes_counter || 0 %>
          
        </div>
        <p class="post_text mx-3"><%= @post.text %></p>
        <%= button_to 'Delete Post', user_post_path(current_user, @post), class: "btn btn-danger mx-3" %>
      </div>
</div>
    <div class="comments_info_container"> 
      <% @post.five_most_recent_comments.each_with_index do |comment, index| %>
        <div class="comment_info">
          <h4> <%= comment.user.name %>'s comment: </h4> 
          &nbsp;&nbsp;
          <p class = 'comment_text'> <%= comment.text %> </p>
        </div>
        <%= button_to 'Delete comment', user_post_comment_path(current_user , @post , comment), method: :delete, class: "btn btn-dark" %>
      <% end %>
    </div>
</div>